const menu = [
  {
    id: 1,
    title: "raw beef",
    category: "beff",
    price: 7.0,
    img: "../images/beefR.jpeg",
    desc: `We sell highest quality beef, the price is per pound and we serve this on wednsday's `,
  },
  {
    id: 8,
    title: "Teff",
    category: "Teff",
    price: 45.0,
    img: "../images/teffM.jpeg",
    desc: `We import Teff, an ingredient to make injera. We have availablity, price is per bag  `,
  },
  {
    id: 3,
    title: "injera",
    category: "",
    price: 10.0,
    img: "../images/injera.jpeg",
    desc: `Freshly prepared injera, price is per bag, Ten piece of injera in a bag`,
  },
  {
    id: 4,
    title: "ethio-african spices",
    category: "spieces",
    price: 10.99,
    img: "../images/ethioAfrican.jpeg",
    desc: `We have plenty of spices to chose from, we import these spices from the origin to give you a good quality`,
  },
  {
    id: 5,
    title: "Sambusa",
    category: "Sambusa",
    price: 1.0,
    img: "../images/sambusa.jpeg",
    desc: `we sell delicious sambusa, fresh and crispy visit our store`,
  },
  {
    id: 6,
    title: "Soda, water drinks",
    category: "",
    price: 1.99,
    img: "./images/soft-drinks.jpeg",
    desc: `To quench your trust, we have variety of selection, stop by in our store`,
  },
  {
    id: 7,
    title: "Spieces",
    category: "",
    price: 8.99,
    img: "../images/spices.jpeg",
    desc: `our selection of spieces, we import from the source, east africa, ethiopia `,
  },

  {
    id: 2,
    title: "clay products",
    category: "",
    price: 10.99,
    img: "../images/ethiopian.jpeg",
    desc: `hand made clay products use for heating up food, incense.`,
  },

  {
    id: 2,
    title: "Kotcho",
    category: "",
    price: 11.99,
    img: "../images/kotcho.webp",
    desc: `our cultural 'kotcho' bread type made from chopped and grated ensete pulp`,
    footer: ``,
  },
];
export default menu;
